name: windows build & test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.1.5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
        
    - name: Build everything
      run: |
        & .\eng\build.ps1 -build $true

    - name: Run unit tests
      run: |
        & .\eng\build.ps1 -build $false -test $true

    - name: Test artifact publishing
      run: |
        & .\eng\build.ps1 -build $false -test $false -publish $true
